### ISSUE TITLE
Backendmodul: template could not be loaded

### ISSUE THREAD

**Issue by jacques2017** [eibiflo/cf_cookiemanager#2]
Hi,
I try to test your extension and load version 1.0.3
In backendmodul the template could not be loaded:

The Fluid template files "/xxx/typo3conf/ext/cf_cookiemanager/Resources/Private/Backend/Partials/BackendTabs/home.html.html", "/xxx/typo3conf/ext/cf_cookiemanager/Resources/Private/Backend/Partials/BackendTabs/home.html", "/xxx/typo3conf/ext/cf_cookiemanager/Resources/Private/Partials/BackendTabs/home.html.html", "/xxx/typo3conf/ext/cf_cookiemanager/Resources/Private/Partials/BackendTabs/home.html" could not be loaded.

**Comment by eibiflo** [comment]
Hello, jacques2017,

Thank you for your message.

Please note that the extension is currently in alpha stage and not suitable for production systems.

Your issue seems to be that you haven't completed the installation. You need to add the Typoscript template to your page template.
Installation instructions: https://docs.typo3.org/p/codingfreaks/cf-cookiemanager/main/en-us/Installation/Index.html

If you encounter any errors or have constructive feedback for me, please contact me directly on Typo3 Slack. https://typo3.slack.com/archives/C04NB2ZP30U

Best Regards
Flo

**Comment by jacques2017** [comment]
Hello Flo,

thank you for your answer. I added the Typoscript template. In the file

Resources\Private\Backend\Templates\CookieSettingsBackend\index.html

you have to delete the ".html" in 
`<f:render>`
Your code:
` <f:render partial="backendTabs/{tab.identifier}.html" arguments="{_all}"></f:render>'

change to

`<f:render partial="backendTabs/{tab.identifier}" arguments="{_all}"></f:render>`

**Comment by eibiflo** [comment]
That's interesting, thank you for the information. I'll take a look as soon as i find time.

In general, I work with the version and code in Git and wasn't able to reproduce the error. 
Do you have any ideas on what could be causing it? Any Typo3script constants settings or something?
What Typo3 Version are you using, im using the latest v11.5.21.

Currently i testet it only with the Bootstrap Demo Site Package.
(Demo: https://cookiedemo.coding-freaks.com/ )

**Comment by jacques2017** [comment]
Thank you for your great work. I correct the issue in my copy of the code and it works fine. 

The partial-name is allway to write without the file-extension if you use <f:render >because the file-extension of a partial is allways ".html"

I use the code from git-hub and not the version from TER

**Comment by eibiflo** [comment]
It was probably a no-brainer. Thanks for the tip and the feedback.
Glad to hear that, I'm open to suggestions for improvement.

I find it interesting that both versions work for my Typo3 installations. But i fixed it now.
