### ISSUE TITLE
Hidden Cookie Services not hidden in editing mode

### ISSUE THREAD

**Issue by anderlk** [eibiflo/cf_cookiemanager#21]
When some Cookie Services are hidden, the objects aren't hidden in editing mode.

There comes an exception:

`PHP Warning: Undefined array key 1 in /var/www/vhosts/httpdocs/typo3conf/ext/cf_cookiemanager/Classes/Utility/HelperUtility.php line 92`

TYPO3 version 12.4.10
cf_cookiemanager version 1.4.3
PHP version: 8.2.14
Classic mode (no composer)

![Bildschirmfoto 2024-01-25 um 19 58 56](https://github.com/eibiflo/cf_cookiemanager/assets/12695520/0cb670bb-3e2a-42e4-93ad-f2f8fa73f934)

![Bildschirmfoto 2024-01-25 um 20 00 20](https://github.com/eibiflo/cf_cookiemanager/assets/12695520/bc9dd104-d4e6-4bed-97e2-6055c25a99e4)

**Comment by eibiflo** [comment]
Thank you for the issue @anderlk.

The problem, as seen in the commit ([[BUGFIX] Respect hidden flag in TCA, fixed issue](https://github.com/eibiflo/cf_cookiemanager/commit/4bfa0f07348499dfedb7922c63398db4060b72cc) https://github.com/eibiflo/cf_cookiemanager/issues/21), was that the hidden flags were not respected in the TCA.

I have done the same for cookie TCA.  
If these are hidden and in use, they must be made visible again through the list module, as I intentionally removed the cookie tab because I found it confusing.
