### ISSUE TITLE
Some cookies don't get deleted

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#25]
Is it possible to delete all cookies, but the cf_cookie after Decline all (Alle ablehnen).
On your website it doesn't seem to be so: https://coding-freaks.com/
<img width="161" alt="image" src="https://github.com/eibiflo/cf_cookiemanager/assets/147737053/b5a39ecc-2d2a-4c2d-a0e7-671d8ffe947c">

**Comment by eibiflo** [comment]
Thanks for pointing this out! 

It looks like this issue might be because of a recent update. It doesn't happen on new installations, so it seems to be about how existing setups are configured.

Here's a quick way to fix it on your site:

Remove the database tables for the Cookie Manager extension.
Recreate the tables using the Typo3 Install Tool.
Follow the Backend Installation Process in the Module tab.

The problem seems to be with the Cookie_service_mm table. This was an issue in the early versions of the Cookie Manager. 
If you've had the extension for a while, we're probably facing the same issue.

The data structure should now be in order and no further changes are needed for the upcoming stable release. 

Please accept my apologies for any inconvenience.
