### ISSUE TITLE
Hide modal box

### ISSUE THREAD

**Issue by stephangrass** [eibiflo/cf_cookiemanager#27]
Is it possible to hide the modal box? I want to use the Cookie Manager to load external content (iFrames, scripts). It's enough here to just disable the corresponding elements if they are on a page.

Thanks
Stephan

**Comment by stephangrass** [comment]
Ok, thanks.
I think for the entire root site is ok.

**Comment by eibiflo** [comment]
I'm currently considering whether it makes sense to place the other configurations at the page root instead of storing them in the extension configuration.

This probably only makes sense for users with multiple sites, but I'm interested in your opinion. "Revision version, cookie expiration, cookie path, hide from bots" - do you think these should be set independently, or would that just be more hassle for the end user?

https://github.com/eibiflo/cf_cookiemanager/blob/main/ext_conf_template.txt

**Comment by stephangrass** [comment]
Hi, I think, place the other configurations at the page root is the better solution. Or in the site-configuration.

**Comment by ChristianOsswald** [comment]
I would need this feature too. As far as i can see it is not implemented yet, to disable the modal box but not other functionality? Maybe I can do a PR for this.

**Comment by eibiflo** [comment]
Hei @ChristianOsswald,

It has already been implemented with [this commit](https://github.com/eibiflo/cf_cookiemanager/commit/915f431750409a85f125b04a49968a02458c661a) and [this one](https://github.com/eibiflo/cf_cookiemanager/commit/d6db986108999e0ce92e2ff6498a8205601d1a85).

The release is scheduled for version 1.6.0, which is planned for today, although it was initially expected last week. 😄 
It's on my list. I just need to verify that the changes are beneficial. If you need it now, you have the option to install the development version or wait until tomorrow.

**Comment by eibiflo** [comment]
I've noticed during testing that when I move "scriptBlocking" to a constant instead of keeping it in the extension config, I can't access it in the middleware. It's pretty strange behavior.

I tried this in the CfHook function:
https://github.com/eibiflo/cf_cookiemanager/blob/main/Classes/Middleware/ModifyHtmlContent.php#L43

```
$configurationManager = GeneralUtility::makeInstance(ConfigurationManager::class);
$fullTypoScript = $configurationManager->getConfiguration(ConfigurationManager::CONFIGURATION_TYPE_FULL_TYPOSCRIPT);
```

Is there a better option? It seems like it doesn't work 100% of the time. Sometimes the value is empty, and then I have to clear the cache for the value to show up again. This shouldn't happen in production, so for now, the option remains in the extension config. 

However, I'd appreciate any feedback you have, or if I'm doing something wrong.

**Comment by ChristianOsswald** [comment]
I think it maybe is, cause typoscript gets loaded later in process.
Maybe "real" site configuration could work: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/ExtendingSiteConfig.html

**Comment by eibiflo** [comment]
I've currently left it in the extension configuration, but I need to look into making it possible in the site config as well, which would definitely be a nice feature. 

The settings are now released with: https://github.com/eibiflo/cf_cookiemanager/releases/tag/v1.6.0

Cheers
