### ISSUE TITLE
Start configuration doesn't work

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#33]
Hello,

I got a problem with the initial start configuration. it doesn't do anything, when I hit the button. Unfortunately I can't see any error message.
![image](https://github.com/eibiflo/cf_cookiemanager/assets/147737053/4b16c610-9f88-46e3-8335-abf7f01bf89d)

TYPO3 11.5.36 | PHP 8.1.27
cf_... datatables are empty.
In another project it worked perfectly. Are there problems with the API at the moment?

**Comment by eibiflo** [comment]
Hei, issues with the API are not known, even if there were, the offline mode should activate since version 1.4.1.
The API is not strictly necessary, the offline datasets suffice for installation by the json files.

When you click on Start Configuration, it should display "Loading.." which is triggered by the Javascript. (https://github.com/eibiflo/cf_cookiemanager/blob/3a5d0511ec141f7a58aca59739d278c8f7818f68/Resources/Public/JavaScript/Backend/initCookieBackend.js#L80)

What you can Try is to execute the Upgrade Wizard from the Typo3 CLI interface.  
(https://github.com/eibiflo/cf_cookiemanager/blob/3a5d0511ec141f7a58aca59739d278c8f7818f68/Classes/Updates/StaticDataUpdateWizard.php) This bypasses the Install Screen. 

The next question would be: 
Do you have any JavaScript errors in the console, or PHP errors in the error log?

Can you Reachte the API from the Server?
Here is a Demo how to test some calls with [swagger.io/](https://editor.swagger.io/): (https://cookieapi.coding-freaks.com/application-programming-interface)

**Comment by ChristianOsswald** [comment]
Hey,
thank you very much. It worked instantly via the TYPO3 Upgrade Wizard :)

**Comment by ChristianOsswald** [comment]
I didnt't have any console errors or typo3 error log entries

**Comment by eibiflo** [comment]
I would still be interested in finding out what exactly triggers an error causing the installation to get stuck. It might indeed be a short timeout, but then the offline installation should have taken over—was that not the case for you?

It's good that the Upgrade Wizard is also accessible from the backend, so you can at least restart the importer, good job! 

For future versions, I'm planning to design a better interface where you can see the assigned languages before the import, and these won't necessarily have to come from the config.yaml.
Then, in that interface, we can also incorporate a failsafe to get more information on what didn't work, if anything.

**Comment by ChristianOsswald** [comment]
It always reappears the initial button, after I see the loading screen for about 1 sec.

**Comment by ChristianOsswald** [comment]
no entry in typo3 log nor in chrome console any errors :(

**Comment by eibiflo** [comment]
What type of Database do you use?
Mariadb or some other? 

If i unterstand this correctly, if you use the wizard in the Install Tool it works fine?

**Comment by ChristianOsswald** [comment]
I start my project with ddev, mariaDB. Same config as other projects, where it already worked.
Yes, install tool works fine.
