### ISSUE TITLE
Dead-end in the tutorial

### ISSUE THREAD

**Issue by Beltshassar** [eibiflo/cf_cookiemanager#34]
Minor detail:
The "next" button on the Layout/Customize step during the tutorial is click-able, but seems to lead to a dead-end.
I would expect the next-button to be disabled, forcing me to click on the "Customize"-pane.

Best Regards

Daniel D.

![image](https://github.com/eibiflo/cf_cookiemanager/assets/15835725/ce45309e-5b97-4b6a-988c-19569ea44926)

**Comment by eibiflo** [comment]
Hi, @Beltshassar  thank you for your issue report. 

The tutorial itself is still fundamentally incomplete. [Example](https://github.com/eibiflo/cf_cookiemanager/blob/main/Resources/Public/JavaScript/TutorialTours/FrontendTour.js#L169)
In my opinion, it needs a complete overhaul. If the click is not performed, I have to simulate it programmatically, otherwise, you end up on the wrong tab or Post Action. This is currently a workaround solution :) 

To be honest, I'm not yet sure how to resolve this better. I would also like to have a "Step Back" button, but that would require me to program all the steps, which I haven't found the time for yet. Do you have any ideas on how to solve this more easily?

**Comment by Beltshassar** [comment]
Hi @eibiflo 

I see. It’s not that it is much of an issue, just wanted to mention it.
I haven’t been making guided tours like this myself, but I’ve used the js-plugin: [https://driverjs.com] / 
[https://github.com/kamranahmedse/driver.js] once for a similar task. It is pretty neat. Though I don’t know if it will play nice with Typo3 BE.

B/R Daniel
