### ISSUE TITLE
Possibility to set cookie service accepted by default (opt-out)

### ISSUE THREAD

**Issue by ChristianOsswald** [eibiflo/cf_cookiemanager#55]
Is there any possibility to set a service accepted and make it possible to deactivate afterwards?
Currently it is possible to set the required checkbox for a whole category, but then you can't deny the services inside.

Do you have any suggestions?

**Comment by eibiflo** [comment]
I'm not at the PC right now, but from what I remember, it's unfortunately not yet possible at the service level. However, I somehow manage it for the Cookie Manager service, but that could inherit from the required category as you say.

What you can already do, is use the JavaScript API to manage individual services.

I'll get back to you tomorrow with more detailed information, but you can have a look at the API maybe it solves your problem. 

https://docs.typo3.org/p/codingfreaks/cf-cookiemanager/main/en-us/Developer/JavascriptAPI/Index.html

**Comment by eibiflo** [comment]
Hei @ChristianOsswald,

i would suggest integrating a checkbox into the service:
"Services activated by default? True/False"

Alternatively, the client side way, you could use the JavaScript API, 
` cc.accept('youtube');`

I would prefer the first option, because it needs no extra code for implementation.
What do you think?

**Comment by ChristianOsswald** [comment]
Hi @eibiflo 
in my opinion, too, a checkbox in the service would be best.

**Comment by ChristianOsswald** [comment]
Hi @eibiflo 
thanks very much for the fast responses.
I tested and think I got a bug. 
![image](https://github.com/user-attachments/assets/57f003ca-4ff3-46c4-9c16-ddcc30b91359)

My service seems to be doubled now.

Another suggestion:
I would name the checkboxes like:
- Checked by default / opt-out
- Readonly / required

**Comment by ChristianOsswald** [comment]
I got another Problem at least in console. 
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/8c787b6a-02ed-4191-b10b-2b688a6169cf">

**Comment by ChristianOsswald** [comment]
Another issue related to the fact the checkbox is enabled by default is maybe, that the service script I insert with type "text/plain" doesn't get the type update, so it's not active by default, despite the checkbox says it.

**Comment by eibiflo** [comment]
Thanks for the feedback @ChristianOsswald, I have a weird question:
Is the service actually duplicated, or is it possibly assigned twice? Could you maybe debug and find out why it's being duplicated, Database Layer, Code Layer? 
It might be an edge case, but I’m not sure since it seems to work fine with my default instance. That would be super helpful.

About the JS issue: Does it come from the cookielessTracking.min.js file?
Could you possibly export a configuration so I can debug it, or can I use the provider directly? If so, which one would that be?

Regarding the last point: This is intentional by design because we cannot/should not activate a third-party service without user consent.

I can only pre.-select what it stores by default save action.
I think we might be violating GDPR if the service is automatically activated.
While we could implement this using the JS API, I don’t think it should be configured this way. 
In my Knowledge, we need user consent first, but I’m not a lawyer.
You can simply move it to "Required," then it should work since it appears to be a necessary service.

**Comment by ChristianOsswald** [comment]
The duplicated service had sth to do with the translated service. I assigned it there, too instead of translating the service. Maybe better set it readonly?
![image](https://github.com/user-attachments/assets/758f7c0a-9e88-4749-a859-95e4466198cd)

Sorry, the js issue had something to do with my custom script.

As far as I know, you can implement services like Matomo or etracker without consent given, but you have to provide an opt-out-option. That's what I am trying to achieve. But it doesn't necessarily have to be a feature of cookiemanager(which I look at as consentmanager). The services shouldn't use cookies...
I can also implement a toggle on the data policy page.

**Comment by eibiflo** [comment]
I'll take a closer look at the first point - make sense :) 



Matomo itself has addressed this case in the FAQ:
https://matomo.org/faq/general/eprivacy-directive-national-implementations-and-website-analytics/

Topic -> Consent Requirement/When Consent Is Not Required

I understand it like: You must obtain consent unless you have a required/essential service.
Matomo itself is not strictly essential, so you should obtain opt-in consent before tracking. 

If you want to load it by default, it gets a bit more complicated because the cookie manager always wants consent first. 
You would need to build something using the JavaScript API.

cc.accept('matomo'), cc.updateScripts() and cc.getUserPreferences() should handle this, but you should only call it on the first visit, else the user consent is not respected if the cf_cookie is prensent, you will override the user-stored settings.

This should do it or? (example google maps accepted by default, and not in required before consent is given)
![image](https://github.com/user-attachments/assets/63ddaada-431b-4701-ae47-8346b71877aa)

**Comment by ChristianOsswald** [comment]
Thanks for the detailed information.
Even more easy imo: Inject the script by default and afterwards let handle the consent tool wether it's loaded or not.

**Comment by ChristianOsswald** [comment]
So, as far as I can see, the feature works for me perfectly.

**Comment by eibiflo** [comment]
Yes, you're right, your solution is more convenient. Just render it directly and let the consent manager handle it. 
However, if it's loaded, it would still execute the request even if declined, or does it handle that properly?

Regarding the read-only field in the backend, I asked in #typo3-cms, because im not sure if we need custom code. [Documentation of allowLanguageSynchronization](https://docs.typo3.org/m/typo3/reference-tca/main/en-us/ColumnsConfig/Type/Inline/Index.html#confval-inline-behaviour-allowlanguagesynchronization).

**Comment by ChristianOsswald** [comment]
if the script is from a local path it gets handled properly. From external url not. I guess that the type text/plain, doesn't get taken into account then.

**Comment by ChristianOsswald** [comment]
Everything fine, thx very much :-)
